version: '2'
services:
  microservice:
    build: .
    image: cloud_native_go:1.0.1
    environment: 
    - PORT=9090
    ports:
    - "9090:9090"
  nginx:
    image: "nginx:1.13.9"
    ports: 
    - "8080:80"
    links:
    - microservice